spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dongbao_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.wukong.mapper
  mapper-locations: classpath:com/wukong/mapper/xml/*.xml
logging:
  level:
    com:
      dongbao:
        msbdongbaoums:
          mapper: debug
server:
  port: 800
